export const projects = [
  {
    id: 1,
    name: 'SpongeFy',
    stacks: ['Angular', 'JavaScript', 'TypeScript', 'HTML & CSS', 'API'],
    deploy: 'https://spongefy.vercel.app',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/spongefy.jpg',
    reposit: 'https://github.com/BenHurAlbertassi12/PortfolioVercel',
    type: 'frontend',
  },
  {
    id: 2,
    name: 'Shopping Cart',
    stacks: ['JavaScript', 'DOM', 'API'],
    deploy: 'https://shopping-cart-fawn-nu.vercel.app',
    reposit: 'https://github.com/BenHurAlbertassi12/shopping-cart',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/trybeShopping.jpg',
    type: 'frontend',
  },
  {
    id: 3,
    name: 'Portifólio',
    stacks: ['JavaScript', 'API', 'HTML & CSS'],
    deploy: 'https://spongefy.vercel.app',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/portifoil.jpg',
    reposit: 'https://github.com/BenHurAlbertassi12/PortfolioVercl',
    type: 'frontend',
  },
  {
    id: 4,
    name: 'App de Receitas',
    stacks: ['React', 'HTML & CSS', 'Context API', 'Hooks', 'API'],
    deploy: 'https://receitasapp.vercel.app/',
    reposit: 'https://github.com/BenHurAlbertassi12/receitasApp',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/receitasApp.jpg',
    type: 'frontend',
  },
  {
    id: 5,
    name: 'Star Wars System',
    stacks: [
      'JavaScript',
      'HTML & CSS',
      'BootsTrap',
      'React',
      'Hooks',
      'Context API',
    ],
    deploy: 'https://starwars-plants.vercel.app',
    reposit: 'https://github.com/BenHurAlbertassi12/StarWarsSystem',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/starwarsplanets.jpg',
    type: 'frontend',
  },
  {
    id: 6,
    name: 'Tryvia',
    stacks: ['JavaScript', 'Redux', 'React', 'HTML & CSS', 'API'],
    deploy: 'https://tryvia-redux-benhur.vercel.com',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/Tryvia.jpg',
    reposit: 'https://github.com/BenHurAlbertassi12/tryviaRedux/tree/main',
    type: 'frontend',
  },
  {
    id: 7,
    name: 'Sistem Solar',
    stacks: ['React', 'Redux', 'HTML & CSS'],
    deploy: 'https://solar-system-pied-gamma.vercel.app',
    reposit: 'https://github.com/BenHurAlbertassi12/SolarSystem',
    imagem:
      'https://raw.githubusercontent.com/BenHurAlbertassi12/PortfolioVercel/main/src/app/data/systemasolar.jpg',
    type: 'frontend',
  },
  {
    id: 8,
    name: 'TryUnfo',
    stacks: ['JavaScript', 'HTML & CSS', 'React', 'Redux', 'API'],
    deploy: 'https://github.com/BenHurAlbertassi12/TryUnfo',
    reposit: 'https://github.com/BenHurAlbertassi12/TryUnfo',
    imagem:
      'https://www.argali.com.br/wp-content/uploads/woocommerce-placeholder.png',
    type: 'frontend',
  },
  {
    id: 9,
    name: 'TrybeWallet',
    stacks: ['Redux', 'JavaScript', 'HTML & CSS', 'React', 'API'],
    deploy: 'https://github.com/BenHurAlbertassi12/Wallet',
    reposit: 'https://github.com/BenHurAlbertassi12/Wallet',
    imagem:
      'https://www.argali.com.br/wp-content/uploads/woocommerce-placeholder.png',
    type: 'frontend',
  },

  {
    id: 30,
    name: 'Trybers&dragons',
    stacks: ['TypeScript', 'POO'],
    deploy: 'https://github.com/BenHurAlbertassi12/Trybers-and-dragons',
    reposit: 'https://github.com/BenHurAlbertassi12/Trybers-and-dragons',
    type: 'backend',
  },
  {
    id: 31,
    name: 'Blogs API',
    stacks: ['Docker', 'Node', 'Express', 'Sequelize', 'JWT', 'Rest'],
    deploy: 'https://github.com/BenHurAlbertassi12/Blogs-Api',
    reposit: 'https://github.com/BenHurAlbertassi12/Blogs-Api',
    type: 'backend',
  },
  {
    id: 32,
    name: 'Trybe Futebol Club',
    stacks: [
      'TypeScript',
      'Node',
      'Express',
      'JWT',
      'Docker',
      'MySQL',
      'Sequelize',
    ],
    deploy: 'https://github.com/BenHurAlbertassi12/TrybeFutebolClub',
    reposit: 'https://github.com/BenHurAlbertassi12/TrybeFutebolClub',
    type: 'backend',
  },
  {
    id: 33,
    name: 'Store Manager',
    stacks: ['MySQL', 'Docker', 'TDD', 'MSC', 'RESTFul'],
    deploy: 'https://github.com/BenHurAlbertassi12/StoreManager',
    reposit: 'https://github.com/BenHurAlbertassi12/StoreManager',
    type: 'backend',
  },
  {
    id: 34,
    name: 'carShop',
    stacks: ['TypeScript', 'POO', 'MongoDB'],
    deploy: 'https://github.com/BenHurAlbertassi12/carShop/',
    reposit: 'https://github.com/BenHurAlbertassi12/carShop/',
    type: 'backend',
  },
  {
    id: 35,
    name: 'Talker Manager',
    stacks: ['Node', 'CRUD', 'API', 'MySQL'],
    deploy: 'https://github.com/BenHurAlbertassi12/talkerManager',
    reposit: 'https://github.com/BenHurAlbertassi12/talkerManager',
    type: 'backend',
  },
  {
    id: 36,
    name: 'TrybeSmith',
    stacks: ['TypeScript', 'POO'],
    deploy: 'https://github.com/BenHurAlbertassi12/trybeSmith',
    reposit: 'https://github.com/BenHurAlbertassi12/trybeSmith',
    type: 'backend',
  },
];
